version: '3'
services:
  node:
    image: node:19.0
    user: node
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "tail -F anything"
    # command: bash -c "npm install && npm run start:dev"
  
  mongo:
    image: mongo:6.0.2
    volumes:
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo_data:/data
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${ROOT_DB_USER}:${ROOT_DB_PASS}@mongo:27017

volumes:
  mongo_data: